name: boreal-wildfire-analysis
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - affine=2.4.0=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h02fc5c5_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=h1d6ff8b_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boltons=23.0.0=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h1cb353e_1
  - bottleneck=1.3.7=py39h4d8bf0d_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bwidget=1.9.14=hce30654_1
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h73a0509_1014
  - cctools_osx-arm64=973.0.1=hef52d2f_12
  - cdsapi=0.5.1=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cf_xarray=0.8.0=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_3
  - cfitsio=4.2.0=h2f961c4_0
  - cftime=1.6.2=py39h4d8bf0d_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - clang=14.0.6=hce30654_0
  - clang-14=14.0.6=default_h81a5282_0
  - clang_osx-arm64=14.0.6=h15773ab_5
  - clangxx=14.0.6=default_hb7ecf47_0
  - clangxx_osx-arm64=14.0.6=he29aa18_5
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - compiler-rt=14.0.6=h30b49de_0
  - compiler-rt_osx-arm64=14.0.6=h48302dc_0
  - contourpy=1.0.7=py39haaf3ac1_0
  - cryptography=39.0.2=py39he2a39a8_0
  - curl=7.88.1=h9049daf_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39h02fc5c5_1
  - dask=2022.12.1=pyhd8ed1ab_0
  - dask-core=2022.12.1=pyhd8ed1ab_0
  - debugpy=1.6.6=py39h23fbdae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2022.12.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - fiona=1.9.1=py39h9e5269e_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.0=py39h02fc5c5_0
  - freetype=2.12.1=hd633e50_1
  - freexl=1.0.6=h1a8c8d9_1
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2023.3.0=pyhd8ed1ab_1
  - gdal=3.6.2=py39h766d3fc_3
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.11.1=hb7217d7_0
  - geotiff=1.7.1=heeaeb2e_5
  - gettext=0.21.1=h0186832_0
  - gfortran_impl_osx-arm64=11.3.0=h2a9d086_31
  - gfortran_osx-arm64=11.3.0=h57527a5_1
  - giflib=5.2.1=h1a8c8d9_3
  - gmp=6.2.1=h9f76cd9_0
  - graphite2=1.3.13=h9f76cd9_1001
  - gsl=2.7=h6e638da_0
  - h5netcdf=1.1.0=pyhd8ed1ab_1
  - h5py=3.7.0=nompi_py39hc9149d8_102
  - harfbuzz=6.0.0=hddbc195_0
  - hdf4=4.2.15=h1a38d6a_5
  - hdf5=1.12.2=nompi_ha7af310_101
  - heapdict=1.0.1=py_0
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.21.2=pyh736e0ef_0
  - ipython=8.11.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - isl=0.25=h9a09cb3_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - json-c=0.16=hc449e50_0
  - jsonpickle=2.2.0=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39h2804cbe_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.4.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kealib=1.5.0=hfd766a6_0
  - kiwisolver=1.4.4=py39haaf3ac1_1
  - krb5=1.20.1=h69eda48_0
  - lcms2=2.15=h481adae_0
  - ld64_osx-arm64=609=h7167370_12
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.0.6=hb7217d7_1
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libclang-cpp14=14.0.6=default_h81a5282_0
  - libcurl=7.88.1=h9049daf_0
  - libcxx=15.0.7=h75e25f2_0
  - libdeflate=1.17=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.6.2=h9bae3ae_3
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran-devel_osx-arm64=11.3.0=hfe9555d_31
  - libgfortran5=12.2.0=h0eea778_31
  - libglib=2.74.1=h4646484_1
  - libiconv=1.17=he4db4b2_0
  - libkml=1.3.0=h41464e4_1015
  - liblapack=3.9.0=16_osxarm64_openblas
  - libllvm11=11.1.0=hfa12f05_5
  - libllvm14=14.0.6=hf6e71e7_1
  - libnetcdf=4.8.1=nompi_h2510be2_106
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h76d750c_0
  - libpq=15.2=h1a28acd_0
  - librttopo=1.1.0=h844f84d_12
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.0.1=h558e587_22
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtiff=4.5.0=h5dffbdd_2
  - libwebp-base=1.3.0=h1a8c8d9_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_3
  - libzip=1.9.2=h76ab92c_1
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.7=h7cfbb63_0
  - llvm-tools=14.0.6=hf6e71e7_1
  - llvmlite=0.39.1=py39h8ca5d33_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py39hb35ce34_0
  - lz4-c=1.9.4=hb7217d7_0
  - make=4.3=he57ea6c_1
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py39h02fc5c5_0
  - matplotlib-base=3.7.1=py39h35e9e80_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.0=he09a6ba_0
  - msgpack-python=1.0.5=py39haaf3ac1_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - nc-time-axis=1.4.1=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.2=py39h053bab8_0
  - networkx=3.0=pyhd8ed1ab_0
  - nlopt=2.7.1=py39h4b514fb_3
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.89=h789eff7_0
  - numba=0.56.4=py39h251cc7c_0
  - numpy=1.23.5=py39hefdcf20_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.0=h03a7124_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.2=py39hde7b980_2
  - pandoc=2.19.2=hce30654_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=h6c112b8_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h8bd98a6_1
  - pint=0.20.1=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - poppler=22.12.0=h9564b9f_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h45c140d_0
  - proj=9.1.0=h13f728c_1
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py39h02fc5c5_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.1=py39h8a4ac70_0
  - pyrsistent=0.19.3=py39h02fc5c5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=hea58f1e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39h02fc5c5_5
  - pyzmq=25.0.1=py39h0553236_0
  - r-abind=1.4_5=r42h142f84f_0
  - r-askpass=1.1=r42h5d63f41_3
  - r-assertthat=0.2.1=r42h6115d3f_0
  - r-backports=1.4.1=r42h5d63f41_1
  - r-base=4.2.2=heabe65b_3
  - r-base64enc=0.1_3=r42h5d63f41_1005
  - r-bit=4.0.5=r42h5d63f41_0
  - r-bit64=4.0.5=r42h5d63f41_1
  - r-blob=1.2.3=r42h6115d3f_0
  - r-boot=1.3_28=r42h6115d3f_0
  - r-broom=0.8.0=r42h6115d3f_0
  - r-bslib=0.3.1=r42h6115d3f_0
  - r-cachem=1.0.7=r42h5d63f41_0
  - r-callr=3.7.0=r42h6115d3f_0
  - r-car=3.1_1=r42hc72bb7e_0
  - r-cardata=3.0_5=r42h142f84f_0
  - r-caret=6.0_93=r42h5d63f41_1
  - r-cellranger=1.1.0=r42h6115d3f_0
  - r-class=7.3_21=r42h5d63f41_0
  - r-cli=3.6.0=r42h9a38a31_0
  - r-clipr=0.8.0=r42h6115d3f_0
  - r-cluster=2.1.4=r42h505ec0b_0
  - r-codetools=0.2_18=r42h6115d3f_0
  - r-colorspace=2.1_0=r42h5d63f41_0
  - r-commonmark=1.8.1=r42h5d63f41_0
  - r-conquer=1.3.3=r42hc33b485_0
  - r-cpp11=0.4.2=r42h6115d3f_0
  - r-crayon=1.5.1=r42h6115d3f_0
  - r-crul=1.2.0=r42h6115d3f_0
  - r-curl=4.3.3=r42h5d63f41_1
  - r-data.table=1.14.6=r42h5b9a8e2_0
  - r-dbi=1.1.2=r42h6115d3f_0
  - r-dbplyr=2.1.1=r42h6115d3f_0
  - r-digest=0.6.31=r42h9a38a31_0
  - r-dplyr=1.1.0=r42h9a38a31_0
  - r-dtplyr=1.2.1=r42h6115d3f_0
  - r-e1071=1.7_13=r42h9a38a31_0
  - r-ellipsis=0.3.2=r42h5d63f41_1
  - r-essentials=4.2=r42hd8ed1ab_2003
  - r-evaluate=0.15=r42h6115d3f_0
  - r-fansi=1.0.4=r42h5d63f41_0
  - r-farver=2.1.1=r42h9a38a31_1
  - r-fastmap=1.1.1=r42h9a38a31_0
  - r-fontawesome=0.2.2=r42h6115d3f_0
  - r-forcats=0.5.1=r42h6115d3f_0
  - r-foreach=1.5.2=r42h6115d3f_0
  - r-foreign=0.8_84=r42h5d63f41_0
  - r-formatr=1.12=r42h6115d3f_0
  - r-fs=1.6.1=r42h9a38a31_0
  - r-future=1.26.1=r42h6115d3f_0
  - r-future.apply=1.9.0=r42h6115d3f_0
  - r-gargle=1.2.0=r42h142f84f_0
  - r-generics=0.1.2=r42h142f84f_0
  - r-ggplot2=3.3.6=r42h6115d3f_0
  - r-gistr=0.9.0=r42h6115d3f_0
  - r-glmnet=4.1_2=r42h505ec0b_1
  - r-globals=0.15.0=r42h142f84f_0
  - r-glue=1.6.2=r42h5d63f41_1
  - r-googledrive=2.0.0=r42h6115d3f_0
  - r-googlesheets4=1.0.0=r42h6115d3f_0
  - r-gower=1.0.1=r42h5d63f41_0
  - r-gtable=0.3.0=r42h6115d3f_0
  - r-hardhat=0.2.0=r42h6115d3f_0
  - r-haven=2.5.2=r42h9a38a31_0
  - r-hexbin=1.28.2=r42h505ec0b_1
  - r-highr=0.9=r42h6115d3f_0
  - r-hms=1.1.1=r42h6115d3f_0
  - r-htmltools=0.5.4=r42h9a38a31_0
  - r-htmlwidgets=1.5.4=r42h6115d3f_0
  - r-httpcode=0.3.0=r42h142f84f_0
  - r-httpuv=1.6.9=r42h9a38a31_0
  - r-httr=1.4.3=r42h6115d3f_0
  - r-ids=1.0.1=r42h142f84f_0
  - r-ipred=0.9_14=r42h5d63f41_0
  - r-irdisplay=1.1=r42h6115d3f_0
  - r-irkernel=1.3=r42_0
  - r-isoband=0.2.7=r42h9a38a31_1
  - r-iterators=1.0.14=r42h6115d3f_0
  - r-jquerylib=0.1.4=r42h6115d3f_0
  - r-jsonlite=1.8.4=r42h5d63f41_0
  - r-kernsmooth=2.23_20=r42h0419871_1
  - r-knitr=1.39=r42h6115d3f_0
  - r-labeling=0.4.2=r42h6115d3f_0
  - r-later=1.3.0=r42h9a38a31_1
  - r-lattice=0.20_45=r42h5d63f41_1
  - r-lava=1.6.10=r42h6115d3f_0
  - r-lazyeval=0.2.2=r42h5d63f41_3
  - r-lifecycle=1.0.1=r42h142f84f_0
  - r-listenv=0.8.0=r42h142f84f_0
  - r-lme4=1.1_32=r42h9a38a31_0
  - r-lobstr=1.1.2=r42h9a38a31_2
  - r-lubridate=1.9.2=r42h5d63f41_1
  - r-magrittr=2.0.3=r42h5d63f41_1
  - r-maps=3.4.1=r42h5d63f41_1
  - r-maptools=1.1_6=r42h5d63f41_0
  - r-mass=7.3_58.3=r42h5d63f41_0
  - r-matrix=1.5_3=r42hb228a35_0
  - r-matrixmodels=0.5_0=r42h6115d3f_0
  - r-matrixstats=0.63.0=r42h5d63f41_0
  - r-mgcv=1.8_42=r42hc857ecf_0
  - r-mime=0.12=r42h5d63f41_1
  - r-minqa=1.2.5=r42h141827b_0
  - r-modelmetrics=1.2.2.2=r42hf53d927_2
  - r-modelr=0.1.8=r42h6115d3f_0
  - r-munsell=0.5.0=r42h6115d3f_0
  - r-nlme=3.1_162=r42h505ec0b_0
  - r-nloptr=2.0.3=r42h141827b_1
  - r-nnet=7.3_18=r42h5d63f41_1
  - r-numderiv=2016.8_1.1=r42h6115d3f_0
  - r-openssl=2.0.6=r42h1bdd256_0
  - r-openxlsx=4.2.5.2=r42h9a38a31_0
  - r-parallelly=1.31.1=r42h6115d3f_0
  - r-pbdzmq=0.3_9=r42hd9ec729_0
  - r-pbkrtest=0.5.1=r42h6115d3f_0
  - r-pillar=1.7.0=r42h6115d3f_0
  - r-pkgconfig=2.0.3=r42h6115d3f_0
  - r-plyr=1.8.8=r42h9a38a31_0
  - r-prettyunits=1.1.1=r42h142f84f_0
  - r-proc=1.18.0=r42h9a38a31_1
  - r-processx=3.8.0=r42h5d63f41_0
  - r-prodlim=2019.11.13=r42h9a38a31_2
  - r-progress=1.2.2=r42h142f84f_0
  - r-progressr=0.10.0=r42h6115d3f_0
  - r-promises=1.2.0.1=r42h9a38a31_1
  - r-proxy=0.4_27=r42h5d63f41_1
  - r-pryr=0.1.6=r42h9a38a31_0
  - r-ps=1.7.2=r42h5d63f41_0
  - r-purrr=0.3.5=r42h5d63f41_1
  - r-quantmod=0.4.20=r42h6115d3f_0
  - r-quantreg=5.94=r42h2920ffe_1
  - r-r6=2.5.1=r42h6115d3f_0
  - r-randomforest=4.7_1.1=r42h505ec0b_1
  - r-rappdirs=0.3.3=r42h5d63f41_1
  - r-rbokeh=0.5.2=r42h6115d3f_0
  - r-rcolorbrewer=1.1_3=r42h6115d3f_0
  - r-rcpp=1.0.10=r42h9a38a31_0
  - r-rcpparmadillo=0.11.4.4.0=r42hb7f35b3_0
  - r-rcppeigen=0.3.3.9.3=r42h55306a0_0
  - r-readr=2.1.4=r42h9a38a31_0
  - r-readxl=1.4.2=r42h815e8a2_0
  - r-recipes=0.2.0=r42h6115d3f_0
  - r-recommended=4.2=r42hd8ed1ab_1005
  - r-rematch=1.0.1=r42h6115d3f_0
  - r-rematch2=2.1.2=r42h142f84f_0
  - r-remotes=2.4.2=r42h142f84f_0
  - r-repr=1.1.4=r42h6115d3f_0
  - r-reprex=2.0.1=r42h6115d3f_0
  - r-reshape2=1.4.4=r42h9a38a31_2
  - r-rio=0.5.29=r42h142f84f_0
  - r-rlang=1.1.0=r42h9a38a31_0
  - r-rmarkdown=2.14=r42h6115d3f_0
  - r-rpart=4.1.19=r42h5d63f41_0
  - r-rstudioapi=0.13=r42h6115d3f_0
  - r-rvest=1.0.2=r42h6115d3f_0
  - r-sass=0.4.5=r42h9a38a31_0
  - r-scales=1.2.0=r42h6115d3f_0
  - r-selectr=0.4_2=r42h6115d3f_0
  - r-shape=1.4.6=r42h142f84f_0
  - r-shiny=1.7.1=r42h6115d3f_0
  - r-sourcetools=0.1.7_1=r42h9a38a31_0
  - r-sp=1.6_0=r42h5d63f41_0
  - r-sparsem=1.81=r42h505ec0b_1
  - r-spatial=7.3_16=r42h5d63f41_0
  - r-squarem=2021.1=r42h142f84f_0
  - r-statmod=1.5.0=r42hcd742af_0
  - r-stringi=1.7.12=r42ha4a7437_0
  - r-stringr=1.4.0=r42h6115d3f_0
  - r-survival=3.5_5=r42h5d63f41_0
  - r-sys=3.4.1=r42h5d63f41_0
  - r-tibble=3.2.0=r42h5d63f41_0
  - r-tidyr=1.2.1=r42h9a38a31_1
  - r-tidyselect=1.1.2=r42h011812f_1
  - r-tidyverse=1.3.1=r42h6115d3f_0
  - r-timechange=0.2.0=r42h9a38a31_0
  - r-timedate=3043.102=r42h6115d3f_0
  - r-tinytex=0.39=r42h142f84f_0
  - r-triebeard=0.4.1=r42h9a38a31_0
  - r-ttr=0.24.3=r42h5d63f41_1
  - r-tzdb=0.3.0=r42h9a38a31_1
  - r-urltools=1.7.3=r42h9a38a31_3
  - r-utf8=1.2.3=r42h5d63f41_0
  - r-uuid=1.1_0=r42h5d63f41_1
  - r-vctrs=0.4.2=r42h9a38a31_1
  - r-viridislite=0.4.0=r42h6115d3f_0
  - r-vroom=1.6.1=r42h9a38a31_0
  - r-withr=2.5.0=r42h6115d3f_0
  - r-xfun=0.37=r42h9a38a31_0
  - r-xml2=1.3.3=r42haf93cbb_2
  - r-xtable=1.8_4=r42h6115d3f_0
  - r-xts=0.13.0=r42h5d63f41_0
  - r-yaml=2.3.7=r42h5d63f41_0
  - r-zip=2.2.2=r42h5d63f41_0
  - r-zoo=1.8_11=r42h5d63f41_1
  - rasterio=1.3.4=py39h69f4551_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rtree=1.0.1=py39hb28b0e7_1
  - scikit-learn=1.2.2=py39h57c6424_0
  - scipy=1.8.1=py39h18313fe_3
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - shapely=2.0.0=py39h472ea82_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h2229b38_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h4d8bf0d_2
  - tapi=1100.0.11=he4954df_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h9bd36d0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tktable=2.10=h4161312_3
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39h02fc5c5_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzcode=2022g=h1a8c8d9_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py39h02fc5c5_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xarray=2022.12.0=pyhd8ed1ab_0
  - xclim=0.40.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h627aa08_1
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=hf913c23_6
prefix: /Users/adam/miniconda3/envs/boreal-wildfire-analysis
